### ISSUE TITLE
Parameter length bug

### ISSUE THREAD

**Issue by gnuy** [gnuy/subdivx-get#2]
Passing a movie name with less than 8 characters in length results in a crash. 

```
$ subdivx-get mulan
panic: runtime error: slice bounds out of range [:-7]

goroutine 1 [running]:
main.extract(0xc000aaa380, 0x335, 0x747b09, 0x7, 0x335, 0x1)
        /home/gabo/go/src/github.com/gnuy/subdivx-get/StringCtl.go:75 +0x199
main.getDate(0xc000c6b04b, 0x32d, 0x32d, 0xc000aaa0cd, 0x1)
        /home/gabo/go/src/github.com/gnuy/subdivx-get/StringCtl.go:60 +0x6c
main.populateElement(0xc000c6b04b, 0x32d, 0x32d, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/gabo/go/src/github.com/gnuy/subdivx-get/Main.go:46 +0x23d
main.main()
        /home/gabo/go/src/github.com/gnuy/subdivx-get/Main.go:81 +0x2bf
```

**Comment by gnuy** [comment]
Solved. The crash happened when another condition, far from character lenght, was met.
